name: bmstu_help
version: 1.0.0+1
publish_to: none
description: Application for helping students study in BMSTU
environment: 
  sdk: '>=3.2.6 <4.0.0'
dependencies: 
  bloc: ^8.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  faker: ^2.0.0
  file_icon: ^1.0.0
  flutter_bloc: ^8.0.0
  flutter_fimber: ^0.7.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  intl: any
  intl_translation: ^0.18.2
  open_file_plus: ^3.4.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  uuid: ^4.3.2
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  lints: ^2.1.1
  pubspec_dependency_sorter: ^1.0.4
  very_good_analysis: ^3.1.0
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/images/
    - assets/images/svg/
  generate: true
  uses-material-design: true
analyzer: 
  errors: 
    invalid_annotation_target: ignore
